### ISSUE TITLE
kebab-bing case-sensitive arguments

### ISSUE THREAD

**Issue by MegaGM** [maarteNNNN/cli-builder#44]
Hi @maarteNNNN Is there any way to address this issue? 
https://github.com/SocketCluster/socketcluster/issues/572

**Comment by maarteNNNN** [comment]
I'll take a look today in the afternoon.

**Comment by maarteNNNN** [comment]
PR https://github.com/SocketCluster/socketcluster/pull/573 fixes your problem.

Commits:
- a3bbeff97b7423c1e417270cf18c98facad8f87b
- d93d3181162ea4cf956895a50696cf6a11357e66

**Comment by MegaGM** [comment]
Thank you for the quick fix!
